### ISSUE TITLE
apiserver-proxy-pod-mutator: Do no remove unknown fields

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/apiserver-proxy#26]
**What would you like to be added**:
This issue is opened by the suggestion in https://github.com/gardener/gardener/issues/6818#issuecomment-1277430381.
In short, in https://github.com/gardener/gardener/issues/6818 we saw that when the `apiserver-proxy-pod-mutator` vendors outdated K8s dependencies, when defaulting a Pod, it removes the fields it does not know (fields added in newer releases).
The suggestion is to rework the webhook to do no remove unknown fields, if possible.

**Why is this needed**:
To prevent the webhook removing unknown fields which leads a Pod obj to fail to be created. See more details in https://github.com/gardener/gardener/issues/6818.

**Comment by ScheererJ** [comment]
The `apiserver-proxy-pod-mutator` was moved to gardener/gardener with https://github.com/gardener/gardener/pull/7980 and eventually removed with https://github.com/gardener/apiserver-proxy/pull/39 from this repository. Therefore, the issue is no longer valid in this repository.

@ialidzhikov Should we move the issue to gardener/gardener?

**Comment by ialidzhikov** [comment]
In gardener/gardener we usually update the k8s.io/* dependencies with (shortly after) the adoption of a new K8s minor version. Hence, moving the webhook to GRM reduces the probability of the above-described issue from occurring.
I rather suggest closing this issue. Let's reopen if we have a new occurrence again. If we have a new occurrence in the future, then I think not only the apiserver-proxy-pod-mutator webhook would be affected.
